version: '3.5'

services:

  provisioning-app:
    container_name: business
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production